// Proxy-stamp classification & geometry. Pure data + functions, no IO.
// Maps each card to one of 16 frame keys, and holds the geometry and label
// spec shared by the CSS overlay and the canvas export.
// Spec: docs/superpowers/specs/2026-07-28-proxy-frame-patches-design.md

export const PROXY_LABEL = 'Proxy';

export const SWATCH_KEYS = [
  'hero-character', 'minion-character',
  'hero-site', 'minion-site', 'balrog-site', 'fw-site',
  'hero-resource', 'minion-resource', 'stage-resource',
  'hazard',
  'red',
  'alatar', 'gandalf', 'pallando', 'radagast', 'saruman',
];

// Covered zone, as fractions of card width/height. One rect for en/es/fr: it
// clears both the left-aligned "©19xx Tolkien Enterprises" (en, es, x to 0.4246)
// and the more-centred French set name, while stopping short of the French
// "Remastérisé…" credit, whose first glyph starts at x 0.4684 and must stay
// readable. The opaque core is x 0.150–0.440, y 0.932–0.975; the rect below adds
// the 7px-at-570 feathered margin baked into each patch PNG.
// Spec: docs/superpowers/specs/2026-07-28-proxy-frame-patches-design.md
export const PROXY_PATCH_RECT = { x: 0.1377, y: 0.9232, w: 0.3146, h: 0.0606 };

// "Proxy" label: Arial Bold, sized like the card's own
// "Remastérisé - Traduction non officielle" line and sitting on its band.
export const PROXY_LABEL_FONT_FRAC = 0.0155;          // of card width
export const PROXY_LABEL_POS = { cx: 0.295, cy: 0.9565 };

// The same label spec expressed in container-query units, for the CSS overlay
// whose container is the patch box (see .proxy-stamp in styles.css). Derived,
// never hand-tuned, so the DOM and canvas paths cannot drift apart.
export const PROXY_LABEL_FONT_CQW = (PROXY_LABEL_FONT_FRAC / PROXY_PATCH_RECT.w) * 100;
export const PROXY_LABEL_DY_CQH =
  ((PROXY_LABEL_POS.cy - (PROXY_PATCH_RECT.y + PROXY_PATCH_RECT.h / 2)) / PROXY_PATCH_RECT.h) * 100;

// Label colour per key: whichever of the two contrasts with that frame's rail.
// Generated by scripts/make_proxy_patches.py (see scripts/proxy-patch-colors.txt)
// and committed as literals so CSS and canvas render identically.
export const PROXY_LABEL_COLOR = {
  'hero-character': '#191919',
  'minion-character': '#F0F0EA',
  'hero-site': '#191919',
  'minion-site': '#F0F0EA',
  'balrog-site': '#F0F0EA',
  'fw-site': '#191919',
  'hero-resource': '#F0F0EA',
  'minion-resource': '#F0F0EA',
  'stage-resource': '#191919',
  'hazard': '#F0F0EA',
  'red': '#F0F0EA',
  'alatar': '#191919',
  'gandalf': '#191919',
  'pallando': '#F0F0EA',
  'radagast': '#191919',
  'saruman': '#191919',
};

// The en/es patch, or the fr variant (the FR card images come from a different
// repository and carry a different colour grade; the offset is baked in).
export function patchUrl(key, lang) {
  return `/proxy-patches/${key}${lang === 'fr' ? '-fr' : ''}.png`;
}

// The four Resource/Dual cards reuse the minion/hero resource frame by name.
const DUAL_BY_NAME = {
  'Tidings of Death': 'minion-resource',
  'Deadly Dart': 'minion-resource',
  'Beasts of the Wood': 'hero-resource',
  'Wild Hounds': 'hero-resource',
};

const WIZARD_NAMES = new Set(['alatar', 'gandalf', 'pallando', 'radagast', 'saruman']);

const BY_TYPE_ALIGNMENT = {
  'Character/Hero': 'hero-character',
  'Character/Minion': 'minion-character',
  'Site/Hero': 'hero-site',
  'Site/Minion': 'minion-site',
  'Site/Balrog': 'balrog-site',
  'Site/Fallen-wizard': 'fw-site',
  'Resource/Hero': 'hero-resource',
  'Resource/Minion': 'minion-resource',
  'Resource/Stage': 'stage-resource',
};

// One of the 16 swatch keys, or null for Regions / unknown combinations
// (null = leave the card unstamped; fail-safe, never a wrong stamp).
export function swatchKeyForCard(card) {
  if (!card || card.type === 'Region') return null;
  const race = (card.attributes && card.attributes.race) || '';
  // The 9 Ringwraiths and The Balrog (BA-3) share one identical red frame.
  // The type guard keeps the 22 Site/Balrog on their own balrog-site frame.
  if (race === 'Ringwraith' || (race === 'Balrog' && card.type === 'Character')) return 'red';
  // Each wizard's frame is identical in its Wizard and Fallen-wizard version.
  // Wizard/Fallen-wizard avatars are keyed by wizard name (same frame in both
  // versions). Any avatar-race card is an avatar, so it never falls through to
  // the generic (type,alignment) frames below.
  if (race === 'Wizard' || race === 'Fallen-wizard') {
    const name = ((card.name && card.name.en) || '').toLowerCase();
    return WIZARD_NAMES.has(name) ? name : null;
  }
  if (card.type === 'Resource' && card.alignment === 'Dual') {
    return DUAL_BY_NAME[(card.name && card.name.en) || ''] || null;
  }
  if (card.type === 'Hazard') return 'hazard';
  return BY_TYPE_ALIGNMENT[`${card.type}/${card.alignment}`] || null;
}
