// Proxy-stamp classification & geometry. Pure data + functions, no IO.
// Maps each card to one of 16 frame keys, and holds the geometry and label
// spec shared by the CSS overlay and the canvas export.
// Spec: docs/superpowers/specs/2026-07-28-proxy-frame-patches-design.md

import { setName } from './lang.js';

export const PROXY_LABEL = 'Proxy';

export const SWATCH_KEYS = [
  'hero-character', 'minion-character',
  'hero-site', 'minion-site', 'balrog-site', 'fw-site',
  'hero-resource', 'minion-resource', 'stage-resource',
  'hazard',
  'red',
  'alatar', 'gandalf', 'pallando', 'radagast', 'saruman',
];

// Covered zone, as fractions of card width/height. One rect for en/es/fr: it
// clears both the left-aligned "©19xx Tolkien Enterprises" (en, es, x to 0.4246)
// and the more-centred French set name, while stopping short of the French
// "Remastérisé…" credit, whose first glyph starts at x 0.4684 and must stay
// readable. The opaque core is x 0.150–0.440, y 0.932–0.975; the rect below adds
// the 7px-at-570 feathered margin baked into each patch PNG.
// These values are the generator's pixel crop box (scripts/make_proxy_patches.py,
// boxes()/build_patch()) transcribed and rounded to 4 dp, not an independent
// derivation - the two are coupled by that transcription, so a future
// recalibration of the generator's crop must update this rect too.
// Spec: docs/superpowers/specs/2026-07-28-proxy-frame-patches-design.md
export const PROXY_PATCH_RECT = { x: 0.1377, y: 0.9232, w: 0.3146, h: 0.0606 };

// "Proxy" label: Arial Bold, sized like the card's own
// "Remastérisé - Traduction non officielle" line and sitting on its band.
// The July calibration derived this from that line's CAP height (≈6.2px at
// 570 width) divided by Arial's cap-height ratio, which undersizes it: the
// real printed line's full glyph extent (ascenders, accents -- what the eye
// actually compares against) measures closer to 9-11px at 570 width. Recut
// against that fuller measurement (2026-08-05); the longest translated set
// name still clears PROXY_PATCH_RECT with 24px to spare at this size.
export const PROXY_LABEL_FONT_FRAC = 0.021;           // of card width
export const PROXY_LABEL_POS = { cx: 0.295, cy: 0.9565 };

// The same label spec expressed in container-query units, for the CSS overlay
// whose container is the patch box (see .proxy-stamp in styles.css). Derived,
// never hand-tuned, so the DOM and canvas paths cannot drift apart.
export const PROXY_LABEL_FONT_CQW = (PROXY_LABEL_FONT_FRAC / PROXY_PATCH_RECT.w) * 100;
export const PROXY_LABEL_DY_CQH =
  ((PROXY_LABEL_POS.cy - (PROXY_PATCH_RECT.y + PROXY_PATCH_RECT.h / 2)) / PROXY_PATCH_RECT.h) * 100;

// Label colour per key: the tone the FR cards actually print their set name in,
// pushed away from the frame only where that tone would be illegible on it.
// Generated by scripts/make_proxy_patches.py (see scripts/proxy-patch-colors.txt,
// whose third column keeps the unfloored FR tint) and committed as literals so
// CSS and canvas render identically.
export const PROXY_LABEL_COLOR = {
  'hero-character': '#4C5A62',
  'minion-character': '#BCB8BC',
  'hero-site': '#68665D',
  'minion-site': '#A9A7A6',
  'balrog-site': '#CAC0BB',
  'fw-site': '#5C5956',
  'hero-resource': '#BEBDBA',
  'minion-resource': '#B9BABC',
  'stage-resource': '#DCE1E0',
  'hazard': '#B7B6B4',
  'red': '#BEBBB9',
  'alatar': '#50585B',
  'gandalf': '#4F4C4A',
  'pallando': '#BEBED2',
  'radagast': '#51433E',
  'saruman': '#7F7B78',
};

// The en/es patch, or the fr variant (the FR card images come from a different
// repository and carry a different colour grade; the offset is baked in).
export function patchUrl(key, lang) {
  return `/proxy-patches/${key}${lang === 'fr' ? '-fr' : ''}.png`;
}

// The four Resource/Dual cards reuse the minion/hero resource frame by name.
const DUAL_BY_NAME = {
  'Tidings of Death': 'minion-resource',
  'Deadly Dart': 'minion-resource',
  'Beasts of the Wood': 'hero-resource',
  'Wild Hounds': 'hero-resource',
};

const WIZARD_NAMES = new Set(['alatar', 'gandalf', 'pallando', 'radagast', 'saruman']);

const BY_TYPE_ALIGNMENT = {
  'Character/Hero': 'hero-character',
  'Character/Minion': 'minion-character',
  'Site/Hero': 'hero-site',
  'Site/Minion': 'minion-site',
  'Site/Balrog': 'balrog-site',
  'Site/Fallen-wizard': 'fw-site',
  'Resource/Hero': 'hero-resource',
  'Resource/Minion': 'minion-resource',
  'Resource/Stage': 'stage-resource',
};

// One of the 16 swatch keys, or null for Regions / unknown combinations
// (null = leave the card unstamped; fail-safe, never a wrong stamp).
export function swatchKeyForCard(card) {
  if (!card || card.type === 'Region') return null;
  const race = (card.attributes && card.attributes.race) || '';
  // The 9 Ringwraiths and The Balrog (BA-3) share one identical red frame.
  // The type guard keeps the 22 Site/Balrog on their own balrog-site frame.
  if (race === 'Ringwraith' || (race === 'Balrog' && card.type === 'Character')) return 'red';
  // Each wizard's frame is identical in its Wizard and Fallen-wizard version.
  // Wizard/Fallen-wizard avatars are keyed by wizard name (same frame in both
  // versions). Any avatar-race card is an avatar, so it never falls through to
  // the generic (type,alignment) frames below.
  if (race === 'Wizard' || race === 'Fallen-wizard') {
    const name = ((card.name && card.name.en) || '').toLowerCase();
    return WIZARD_NAMES.has(name) ? name : null;
  }
  if (card.type === 'Resource' && card.alignment === 'Dual') {
    return DUAL_BY_NAME[(card.name && card.name.en) || ''] || null;
  }
  if (card.type === 'Hazard') return 'hazard';
  return BY_TYPE_ALIGNMENT[`${card.type}/${card.alignment}`] || null;
}

// What a card's stamp shows, or null when it takes no stamp at all.
//
// en/es always mask the copyright notice: it must never reach a print run,
// whatever the user intended, so the checkbox no longer decides WHETHER there
// is a mask for those two languages -- only what caption sits on it. "Proxy"
// for an actual proxy print; otherwise the set's own translated name, which is
// what the FR cards print in that exact spot anyway.
//
// fr keeps the original behaviour untouched (no stamp unless proxy mode is on)
// because the FR images carry the set name there instead of a copyright line,
// so there is nothing that has to be hidden.
export function proxyStampFor(card, lang, proxyMode, setNames) {
  const key = swatchKeyForCard(card);
  if (!key) return null;
  if (lang === 'fr' && !proxyMode) return null;
  const text = proxyMode ? PROXY_LABEL : setName(setNames, card.setCode, lang);
  return { key, text, color: PROXY_LABEL_COLOR[key] };
}
